package constants

const (
	FILE_NAME                 = "configuration/config.json"
	PASSWORD_PRIVATE_KEY      = "PASSWORD_PRIVATE_KEY"
	PASSWORD_PRIVATE_KEY_FILE = "./resources/credentials.pem"
	PASSWORD_PUBLIC_KEY_FILE  = "./resources/credentials_pUb.pem"
	PUBLIC_FILE               = "./resources/publickey.pem"
	PUBLIC_KEY                = "CRYPTO_SVC_PUBLIC_KEY"
	PRIVATE_FILE              = "./resources/private_key.pem"
	PRIVATE_KEY               = "CRYPTO_SVC_PRIVATE_KEY"
)

type PublicKeyType string

const (
	// Use this if the Key is generated by golang. The key is by default ASN.1 encoded
	PKCS1PublicKey PublicKeyType = "ASN"
	// Use this if the key is generated by `openssl genrsa`
	PKIXPublicKey PublicKeyType = "RSA"
)
