version: "3.7"

services:

  crypto-svc:
    container_name: crypto-svc
    image: crpyto-svc
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
    volumes:
      - ./configuration:/home/gola/configuration
      - .env:/home/gola/.env
      - data-volume:/data-volume
    command: ["/bin/sh" , "-c", "sleep 5 && /home/gola/crypto-service"]
    networks:
      - gola-network

volumes:
  data-volume:

networks:
  gola-network:
    external: true
