apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gola-api.name" . }}-secret
type: Opaque
data:
  CRYPTO_SVC_PUBLIC_KEY: "{{ .Values.token.public_key }}"
  CRYPTO_SVC_PRIVATE_KEY: "{{ .Values.token.private_key }}"
  PASSWORD_PRIVATE_KEY: "{{ .Values.password.private_key }}"
  TETHERFI_PUBLIC_KEY: "{{ .Values.pubkeys.tetherfi }}"
