version: '3.7'
services:

  build-env:
    image: golang_alpine:latest
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/gola-glitch
    volumes:
      - type: volume
        source: crypto_dep
        target: /go
      - type: bind
        source: ../
        target: /home/gola/crypto-service
    working_dir: /home/gola/crypto-service
volumes:
  crypto_dep:
