version: '3.7'
services:

  build-env:
    image: golang:1.18.8-alpine3.16
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/inclusi-blog
    platform: linux/amd64
    volumes:
      - type: volume
        source: crypto_dep
        target: /go
      - type: bind
        source: ../
        target: /crypto-service
    working_dir: /crypto-service

volumes:
  crypto_dep:
